---
title: "Check Pdr5 and Pdr 3"
author: "Simone Zaghen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    toc: true
    number_section: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../results/") })

---

# Load packages

```{r, results='hide', message=FALSE}
#Load packages from CRAN
library("tidyverse")
library("reshape2")
library("conflicted")

#Solve conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

```

# Load dataset and filter data 

```{r, results='hide', message=FALSE}
rawdata <- read_tsv("../data/2021_RAPA_TIMECOURSE.tsv.gz") #load raw data
metadata <- read_tsv("../data/Cell_Cycle_Metadata.tsv.gz") #cell cycle data

```

Do some data wrangling

```{r}
df <- cbind(rawdata, metadata) #merge data and metadata

df <- df %>%
  filter(Pool %in% c("1", "2")) %>% #timepoints before rapamycin treatment
  filter(Gene %in% "WT") %>% #only wt strain
  drop_na() %>%
  mutate(max = max(Cell_Cycle_Time), 
         min = min(Cell_Cycle_Time), 
         width = (max-min)/30, 
         bin1 = ceiling((Cell_Cycle_Time-min)/width),
         time_interval = ifelse(Cell_Cycle_Time==min, bin1 + 1, bin1)) %>%
  select(-c("max", "min", "width", "bin1"))

df_meta <- df[,5844:5850]
df_norm <- df[1:5843]*10000/rowSums(df[1:5843]) #normalize

df_norm <- cbind(df_meta, df_norm)

```

```{r}
df_genes <- df_norm %>%
  select(c("YBL005W", #select PDR3
           "YOR153W", #select PDR5
           "Cell_Cycle_Phase", "Cell_Cycle_Time", "time_interval"))

```

```{r}
df_genes %>%
  ggplot(aes(x = factor(time_interval*3),
             y = log10(YOR153W))) +
  geom_boxplot() +
  ylab("log10 (PDR5)") +
  xlab("time") +
  ggtitle("PDR5")
  
df_genes %>%
  ggplot(aes(x = factor(time_interval*3),
             y = log10(YBL005W))) +
  geom_boxplot() +
  ylab("log10 (PDR3)") +
  xlab("time") +
  ggtitle("PDR3")

```

```{r}
df_genes$Cell_Cycle_Phase <- factor(df_genes$Cell_Cycle_Phase,
                                    levels = c("G1", "S", "G2", "M", "M-G1"))


df_genes %>%
  ggplot(aes(x = Cell_Cycle_Phase,
             y = log10(YOR153W))) +
  geom_boxplot() +
  ylab("log10 (PDR5)") +
  xlab("time") +
  ggtitle("PDR5")
  
df_genes %>%
  ggplot(aes(x = Cell_Cycle_Phase,
             y = log10(YBL005W))) +
  geom_boxplot() +
  ylab("log10 (PDR3)") +
  xlab("time") +
  ggtitle("PDR3")

```


